parameters:
#    harvest_cloud_invoice.example.class: HarvestCloud\InvoiceBundle\Example

services:
#    harvest_cloud_invoice.example:
#        class: %harvest_cloud_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
